### ISSUE TITLE
Cannot open Euler field in visit

### ISSUE THREAD

**Issue by mmcgurn** [UBCHREST/petscXdmfGenerator#5]

**Comment by knepley** [comment]
Is the field there in the HDF5? Is it in the XDMF? I do not have Visit installed to check that it understands the XDMF.

**Comment by mmcgurn** [comment]
It is in the HDF5 and the XDMF converter treats it as a single 4D field.  Visit appears to be able to open it, but for some reason it duplicates the 1st field twice and ignores the last.  I think I'll just separate them out in the converter like you did in the python.
